steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/thumbtaro:$COMMIT_SHA', '.']

images: ['asia.gcr.io/$PROJECT_ID/thumbtaro:$COMMIT_SHA']

options:
  machineType: 'E2_HIGHCPU_32'

timeout: 1200s
